# Set tmux to use zsh instead of bash
# set-option -g default-shell /usr/local/bin/zsh
set -g default-command "reattach-to-user-namespace -l /usr/local/bin/zsh"
# Allows for faster key repetition
set -sg escape-time 0

# Status
set -g status-bg black
set -g status-fg white
set -g status-left ' #S'
set -g status-left-fg yellow
#set -g status-left '#[fg=green]#H'
set -g status-right ''
# Highlight active window
setw -g window-status-current-bg blue
# Set window notifications
setw -g monitor-activity off
set -g visual-activity off
# Rename unnamed windows to name of running program
setw -g automatic-rename off
set -g allow-rename off
# Give window tab labels a cleaner look
set -g window-status-format "  #W  "
set -g window-status-current-format "  #W  "
# Maximum length
set -g status-left-length 30
# Start numbering at 1 instead of 0
set -g base-index 1
# Rather than constraining window size to the maximum size of any client
# connected to the *session*, constrain window size to the maximum size of any
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

bind-key a send-prefix

