  set nocompatible

  if filereadable(expand("~/.vimrc.before"))
    source ~/.vimrc.before
  endif

" ================ General Config ====================
" set number                     "Line numbers
  set backspace=indent,eol,start "Allow backspace in insert mode
  set history=1000               "Store lots of :cmdline history
  set ruler                      " Line and column number
  set guicursor=a:blinkon0       "Disable cursor blink
  set visualbell                 "No sounds
  set autoread                   "Reload files changed outside vim
  set hidden                     "Hide abandoned buffers

  syntax on                      "turn on syntax highlighting

  let mapleader=','              "Map <Leader> to ','

" =============== Vundle Initialization ===============
  if filereadable(expand("~/.vim/vundles.vim"))
    source ~/.vim/vundles.vim
  endif

" ================ Turn Off Swap Files ==============
  set noswapfile
  set nobackup
  set nowritebackup

" ================ Persistent Undo ==================
  silent !mkdir -p ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile

" ================ Indentation ======================
" set autoindent
  set smartindent
" set smarttab
  set shiftwidth=2
  set softtabstop=2
  set tabstop=2
  set expandtab

  filetype plugin on
  filetype indent on

" Display tabs and trailing spaces visually
  set list listchars=tab:\ \ ,trail:·

" set nowrap       "Don't wrap lines
" set linebreak    "Wrap lines at convenient points

" ================ Folds ============================
" set foldmethod=indent   "fold based on indent
" set foldnestmax=3       "deepest fold is 3 levels
" set nofoldenable        "dont fold by default

" ================ Completion =======================
" set wildmode=list:longest
" set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
" set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing
" set wildignore+=*vim/backups*
" set wildignore+=*sass-cache*
" set wildignore+=*DS_Store*
" set wildignore+=vendor/rails/**
" set wildignore+=vendor/cache/**
" set wildignore+=*.gem
" set wildignore+=log/**
" set wildignore+=tmp/**
" set wildignore+=*.png,*.jpg,*.gif

" ================ Scrolling ========================
  set scrolloff=8      "Start scrolling when we're 8 lines away from margins
" set sidescrolloff=15
" set sidescroll=1

  set background=dark

  let g:solarized_termtrans = 1
  colorscheme solarized
  call togglebg#map("<F6>")

  set incsearch
  set hlsearch

  set fileformats=unix,dos,mac

  set splitbelow
  set splitright

  set mouse=a "Set marker and text using mouse

" fixes: vim-airline doesn't appear until I create a new split
  set laststatus=2
  set noshowmode

  set runtimepath^=~/.vim/bundle/ctrlp.vim

  set fillchars+=vert:\  " Hide Horizontal split delimiter

" dictionary with the powerline symbols.
  let g:airline_powerline_fonts = 1

" let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|public'
  let g:ctrlp_custom_ignore = '.svn'
  let g:ctrlp_max_files = '10000'

" netrw hide vim files
  let g:netrw_list_hide= '\.*\.swp$,\.*un\~$'

  nnoremap <C-J> <C-W><C-J>
  nnoremap <C-K> <C-W><C-K>
  nnoremap <C-L> <C-W><C-L>
  nnoremap <C-H> <C-W><C-H>

" Use xmpfilter to evalutate ruby inside vim with # =>
  nmap <buffer> <Leader>xm <Plug>(xmpfilter-mark)
  nmap <buffer> <Leader>xx <Plug>(xmpfilter-run)
  nmap <buffer> <Leader>xmp <Leader>xm<Leader>xx

  autocmd Filetype rust         setl ts=4 sts=4 sw=4
" autocmd Filetype javascript  setl sts=0 noexpandtab

  au BufNewFile,BufRead Makefile setl tabstop=4 noet sts=0 sw=4
  au BufNewFile,BufRead Gemfile,Guardfile,Thorfile,*.rabl,*.thor set filetype=ruby
  au BufNewFile,BufRead *.ejs  set filetype=html
  au BufNewFile,BufRead *.skim set filetype=slim
  au BufNewFile,BufRead *.bats set filetype=sh

  " git gutter
  highlight SignColumn ctermbg=10
  highlight SpecialKey ctermbg=0
